n = input('digite qualuqer coisa: ')
print('Ele pode ser considerado um número? ')
print(n.isnumeric())
print('ele pode ser considerado uma letra? ')
print(n.isalpha())
print('ele pode ser considerado alfanumerico? ')
print(n.isalnum())
print('ele está em caracteres minúsculos?')
print(n.islower())
print('e maiúsculos?')
print(n.isupper())
print('é um número decimal?')
print(n.isdecimal())
print('é somente espaço? ')
print(n.isspace())

