print('multiplication table')
n = int(input('give me a integer number: '))
c = 0
r = n * (c)
print('{} multiplied by {} is {}'.format(n, c, r))
r = n * (c + 1)
print('{} multiplied by 1 is {}'.format(n, r))
r = n * (c + 2)
print('{} multiplied by 2 is {}'.format(n, r))
r = n * (c + 3)
print('{} multiplied by 3 is {}'.format(n, r))
r = n * (c + 4)
print('{} multiplied by 4 is {}'.format(n, r))
r = n * (c + 5)
print('{} multiplied by 5 is {}'.format(n, r))
r = n * (c + 6)
print('{} multiplied by 6 is {}'.format(n, r))
r = n * (c + 7)
print('{} multiplied by 7 is {}'.format(n, r))
r = n * (c + 8)
print('{} multiplied by 8 is {}'.format(n, r))
r = n * (c + 9)
print('{} multiplied by 9 is {}'.format(n, r))
r = n * (c + 10)
print('{} multiplied by 10 is {}'.format(n, r))